# Generated by Django 2.2.5 on 2019-11-21 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp_nombre', models.CharField(max_length=100, verbose_name='Nombre Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_nombre', models.CharField(max_length=350, verbose_name='Nombre del evento')),
                ('event_imagen', models.ImageField(upload_to='imgEventos/', verbose_name='Imagen promocional del evento')),
                ('event_fecha_inicial', models.DateField(verbose_name='Fecha inicial del evento')),
                ('event_fecha_final', models.DateField(verbose_name='Fecha final del evento')),
                ('event_ubicacion', models.CharField(max_length=800, verbose_name='Direccion del evento')),
                ('event_hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('event_hora_fin', models.TimeField(verbose_name='Hora de fianlización')),
                ('event_patrocinado', models.CharField(max_length=800, verbose_name='Patrocinado por')),
                ('event_especificacion', models.CharField(max_length=250, verbose_name='Especificaciones adicionales')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_nombre', models.CharField(max_length=100, verbose_name='Nombre Marca')),
                ('marca_img', models.ImageField(upload_to='marca_img/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='CorreoCco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corr_nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('corr_email', models.EmailField(max_length=300, verbose_name='Email')),
                ('corr_telefono', models.CharField(max_length=10, verbose_name='Número teléfonico')),
                ('corr_asunto', models.CharField(max_length=150, verbose_name='Asunto')),
                ('corr_mensaje', models.CharField(max_length=700, verbose_name='Escriba aqui su mensaje')),
                ('corr_crado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('corr_depo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='compucopias.Departamento', verbose_name='Departamento al que se dirige')),
            ],
            options={
                'verbose_name': 'Correos de contacto',
            },
        ),
    ]
